### ISSUE TITLE
"not implemented: Item::Macro2" panic when trying to print libcore

### ISSUE THREAD

**Issue by vi** [dtolnay/prettyplease#18]
I expect not yet supported features (e.g. macro by example v2) to be printed unprettily instead of panicking.

```
thread 'main' panicked at 'not implemented: Item::Macro2 `macro assert_matches { ($ left : expr , $ (|) ? $ ($ pattern : pat_param) |+ $ (if $ guard : expr) ? $ (,) ?) => { match $ left { $ ($ pattern) |+ $ (if $ guard) ? => { } ref left_val => { $ crate :: panicking :: assert_matches_failed (left_val , $ crate :: stringify ! ($ ($ pattern) |+ $ (if $ guard) ?) , $ crate :: option :: Option :: None) ; } } } , ($ left : expr , $ (|) ? $ ($ pattern : pat_param) |+ $ (if $ guard : expr) ?, $ ($ arg : tt) +) => { match $ left { $ ($ pattern) |+ $ (if $ guard) ? => { } ref left_val => { $ crate :: panicking :: assert_matches_failed (left_val , $ crate :: stringify ! ($ ($ pattern) |+ $ (if $ guard) ?) , $ crate :: option :: Option :: Some ($ crate :: format_args ! ($ ($ arg) +))) ; } } } , }`', /home/vi/.cargo/registry/src/-3d9d141e372ea94e/prettyplease-0.1.10/src/item.rs:169:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff/library/core/src/panicking.rs:142:14
   2: prettyplease::item::<impl prettyplease::algorithm::Printer>::item
   3: prettyplease::item::<impl prettyplease::algorithm::Printer>::item_mod
             at /home/vi/.cargo/registry/src/-3d9d141e372ea94e/prettyplease-0.1.10/src/item.rs:183:17
   4: prettyplease::item::<impl prettyplease::algorithm::Printer>::item
             at /home/vi/.cargo/registry/src/-3d9d141e372ea94e/prettyplease-0.1.10/src/item.rs:25:32
   5: prettyplease::file::<impl prettyplease::algorithm::Printer>::file
             at /home/vi/.cargo/registry/src/-3d9d141e372ea94e/prettyplease-0.1.10/src/file.rs:13:13
   6: prettyplease::unparse
             at /home/vi/.cargo/registry/src/-3d9d141e372ea94e/prettyplease-0.1.10/src/lib.rs:373:5
   7: syn_file_expand_cli::main
             at ./crates/syn-file-expand-cli/src/main.rs:140:28
   8: core::ops::function::FnOnce::call_once
             at /rustc/c0672870491e84362f76ddecd50fa229f9b06dff/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted
```

**Comment by dtolnay** [comment]
This has to do with use of "decl_macro" / the `macro` keyword.

The initiative around `macro` keyword lost steam at least 4 years ago so I am not planning to support it. Generated code should not be using that syntax.

**Comment by vi** [comment]
libstd/libcore does use it though. Other nightly-only crates may use some future nightly-only features.

What about avoiding panic when unimplemented item is encountered? Shall there be a fallback for those cases, to render most of the code prettily barring the unsupported parts?

**Comment by dtolnay** [comment]
I would not want a fallback in this crate. The intention is to support code generators and they are in control of what code to generate. I think this falls under "intended to accommodate hand-maintained source code" in the readme; that code you are referring to in libstd/libcore is handwritten code.
